<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="INsaikrisv.local" name="Test" tests="8" failures="4" timestamp="16 Nov 2015 22:32:12 GMT" time="0.195" errors="0">
  <testcase name="testApp on [SampleTest passed=0 failed=0 skipped=0]" time="0.001" classname="com.test.sample.SampleTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.test.sample.SampleTest.testApp(SampleTest.java:15)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testApp on [SampleTest passed=0 failed=0 skipped=0] -->
  <testcase name="testApp4 on [Sample2Test passed=0 failed=0 skipped=0]" time="0.001" classname="com.test.sample.Sample2Test">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.test.sample.Sample2Test.testApp4(Sample2Test.java:13)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testApp4 on [Sample2Test passed=0 failed=0 skipped=0] -->
  <testcase name="testApp5 on [Sample2Test passed=0 failed=0 skipped=0]" time="0.0" classname="com.test.sample.Sample2Test"/>
  <testcase name="testApp1 on [SampleTest passed=0 failed=0 skipped=0]" time="0.0" classname="com.test.sample.SampleTest"/>
  <testcase name="testApp6 on [Sample2Test passed=0 failed=0 skipped=0]" time="0.0" classname="com.test.sample.Sample2Test">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.test.sample.Sample2Test.testApp6(Sample2Test.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testApp6 on [Sample2Test passed=0 failed=0 skipped=0] -->
  <testcase name="testApp2 on [SampleTest passed=0 failed=0 skipped=0]" time="0.0" classname="com.test.sample.SampleTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.test.sample.SampleTest.testApp2(SampleTest.java:25)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testApp2 on [SampleTest passed=0 failed=0 skipped=0] -->
  <testcase name="testApp7 on [Sample2Test passed=0 failed=0 skipped=0]" time="0.0" classname="com.test.sample.Sample2Test"/>
  <testcase name="testApp3 on [SampleTest passed=0 failed=0 skipped=0]" time="0.0" classname="com.test.sample.SampleTest"/>
</testsuite> <!-- Test -->
